/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionetudiants;

import Models.Etudiant;
import gestionetudiants.Controllers.EtudiantsController;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walidsassi
 */
public class EtudiantsManagerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EtudiantsManagerJFrame
     */
    // j'ai commencé par définir le controlleur en tant que variable global ou attribut au sens de java 
    EtudiantsController Vc;
    Boolean MatriculeIsValide;// variable qui permet de valider l'état de la matricule
    Boolean NameIsValide;// variable qui valide le nom 
    public EtudiantsManagerJFrame() {
        initComponents();
        // lecture de données depuis la base mysql et affichage dans le Jtable
        initData();
        // initialisation de labels d'errors
        initErrorsLabels();// par défaut les lables sont invisibles
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // initialisation des Labels erronées
    public void initErrorsLabels(){
        MatriculeErrorLabel.setVisible(false);
        NameErrorLabel.setVisible(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelStudent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MatriculeTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NomTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PrenomTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SectionCombo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jDateBirthday = new com.toedter.calendar.JDateChooser();
        MatriculeErrorLabel = new javax.swing.JLabel();
        NameErrorLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        StudentsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        SearchCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion des étudiants");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Gestion des étudiants");

        jPanelStudent.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations de l'étudiant"));

        jLabel2.setText("Matricule");

        MatriculeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MatriculeTextFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("Nom");

        NomTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomTextFieldKeyPressed(evt);
            }
        });

        jLabel4.setText("Prénom");

        jLabel5.setText("Section");

        SectionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI1", "SI2", "SI3", "MPTRT", "MPSSR", "MRSI" }));

        jLabel6.setText("Date de Naissance");

        MatriculeErrorLabel.setBackground(new java.awt.Color(255, 0, 51));
        MatriculeErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        MatriculeErrorLabel.setForeground(new java.awt.Color(204, 0, 102));
        MatriculeErrorLabel.setText("La Matricule erronée!!!");

        NameErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        NameErrorLabel.setForeground(new java.awt.Color(255, 0, 102));
        NameErrorLabel.setText("Le Nom érronné!!!");

        javax.swing.GroupLayout jPanelStudentLayout = new javax.swing.GroupLayout(jPanelStudent);
        jPanelStudent.setLayout(jPanelStudentLayout);
        jPanelStudentLayout.setHorizontalGroup(
            jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(SectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStudentLayout.createSequentialGroup()
                        .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelStudentLayout.createSequentialGroup()
                                .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NameErrorLabel))
                            .addGroup(jPanelStudentLayout.createSequentialGroup()
                                .addComponent(MatriculeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MatriculeErrorLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStudentLayout.setVerticalGroup(
            jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MatriculeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MatriculeErrorLabel))
                .addGap(31, 31, 31)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameErrorLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PrenomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(SectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste des étudiants"));

        StudentsTable.setBackground(new java.awt.Color(204, 204, 204));
        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matricule", "Nom", "Prenom", "Section", "Date de naissance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(StudentsTable, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opérations"));

        AddBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionetudiants/Icones/ajouter.png"))); // NOI18N
        AddBtn.setText("Ajouter");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionetudiants/Icones/supprimer.png"))); // NOI18N
        DeleteBtn.setText("Supprimer");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionetudiants/Icones/modifier.png"))); // NOI18N
        UpdateBtn.setText("Modifier");

        ClearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionetudiants/Icones/actualiser.png"))); // NOI18N
        ClearBtn.setText("Actualiser");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateBtn)
                    .addComponent(ClearBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddBtn, DeleteBtn});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N

        SearchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matricule", "Section", " " }));

        jLabel7.setText("Par:");

        SearchBtn.setText("Rechercher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(SearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBtn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 306, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // récupération des données depuis la base au démarrage de la fenêtre
    private void initData(){
         Vc = new EtudiantsController();
        DefaultTableModel model = new DefaultTableModel(new String[]{"CIN", "Nom", "Prenom","Section","Date de naissance"}, 0);
                // je lance maintenant ma requête, toujours les requêtes dans le contrôlleur c'est le principe de MVC
                // on récupére un resultSet {un ensemble d'enregistrement(tuples) de notre table}
                ResultSet rs = Vc.GetStudents();
        try {
            // On commence le parcours de cet ensemble d'enregistrements
            while(rs.next()){
                int cin = rs.getInt("Cin");// il faut veiller que le nom et les types des champs récupéré coincident avec celles en BD
                String nom = rs.getString("Nom");
                String prenom = rs.getString("Prenom");
                String section = rs.getString("Section");
                Date naissance = rs.getDate("DateNaissance");
                model.addRow(new Object[]{cin, nom, prenom,section,naissance});// ajouter ces élèments au model de la Jtable
            }
        } catch (SQLException ex) {
            Logger.getLogger(EtudiantsManagerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            // en fin de parcours on insère ce modele dans la Jtable
            StudentsTable.setModel(model);
    }
    // code de la fonction de vérification
    private boolean verifyForm(){
        return MatriculeIsValide && NameIsValide;// comment alors vérifier l'état des zones de textes en temps réel !!!!
    }
    // ici le code du clique sur le bouton ajouter 
    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        // ajout d'une méthode de vérification ici
        // l'ajout ne sera effectué si et seulement si la méthode verifyForm retourne vrai 
        if (verifyForm()){
        Etudiant e;
        //J'ai commencé par instancier un objet étudiant qui contiendra tous les informations prises de la vue (mon EtudiantManagerJframe)
        // créer un objet étudiant avec les données des différents composants Swing
        e = new Etudiant(Integer.parseInt(MatriculeTextField.getText()), NomTextField.getText(), PrenomTextField.getText(), SectionCombo.getSelectedItem().toString(), jDateBirthday.getCalendar().getTime());
//Créer un objet de type EtuidantsController qui constitue le controlleur qui va insérer les données dans la base mysql et aussi les récupérer 
// je garde dans ma tête cette idée de découplage entre la vue et le controlleur et le modéle il ne faut pas agir sur la base depuis la vue
//il faur que le controlleur agit tout seul sur les données de la base.
       // en cas de succées on agit sur notre jTable afin d'afficher les données 
       if (Vc.addStudent(e)){
            try {
                // tout d'abord je commence par la création du modele de notre Jtable
                DefaultTableModel model = new DefaultTableModel(new String[]{"CIN", "Nom", "Prenom","Section","Date de naissance"}, 0);
                // je lance maintenant ma requête, toujours les requêtes dans le contrôlleur c'est le principe de MVC
                // on récupére un resultSet {un ensemble d'enregistrement(tuples) de notre table}
                ResultSet rs = Vc.GetStudents();
                // On commence le parcours de cet ensemble d'enregistrements
                while(rs.next()){
                    int cin = rs.getInt("Cin");// il faut veiller que le nom et les types des champs récupéré coincident avec celles en BD
                    String nom = rs.getString("Nom");
                    String prenom = rs.getString("Prenom");
                    String section = rs.getString("Section");
                    Date naissance = rs.getDate("DateNaissance");
                    model.addRow(new Object[]{cin, nom, prenom,section,naissance});// ajouter ces élèments au model de la Jtable
                }   
            // en fin de parcours on insère ce modele dans la Jtable
            StudentsTable.setModel(model);
            } catch (SQLException ex) {
                Logger.getLogger(EtudiantsManagerJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
       }  
    }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed
    // controller la saisie de la matricule 
    private void MatriculeTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatriculeTextFieldKeyPressed
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        // on récupére ç travers l'évenement keyevent chaque caractère saisie et on vérifie si il est un chiffre ou non ???
        if (!(Character.isDigit(car))){
            MatriculeErrorLabel.setVisible(true);// en cas d'erreur 
            MatriculeIsValide = false;
        }else{
            MatriculeErrorLabel.setVisible(false);// en cas de non erreur
            MatriculeIsValide = true;
        }
    }//GEN-LAST:event_MatriculeTextFieldKeyPressed
/// Controller la saisie du nom 
    private void NomTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomTextFieldKeyPressed
        // TODO add your handling code here:
        // de la même manière pour le nom qui doit contenir que des lettres 
        char car = evt.getKeyChar();
        if (!(Character.isLetter(car))){
            NameErrorLabel.setVisible(true);
            NameIsValide = false;
        }else{
            NameErrorLabel.setVisible(false);
            NameIsValide = true;
        }
    }//GEN-LAST:event_NomTextFieldKeyPressed
    // voyons maintenant la simulation Dans cette première partie vous remarquez qu'on peut vérifier en temps réel l'état de nos textfield avant
    // la soumission dans la base. Essayer toujours d'intialiser le contenu de la frame en utilisant des méthodes de genre InitData
    // à la prochaine vidéo
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EtudiantsManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EtudiantsManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EtudiantsManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EtudiantsManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EtudiantsManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel MatriculeErrorLabel;
    private javax.swing.JTextField MatriculeTextField;
    private javax.swing.JLabel NameErrorLabel;
    private javax.swing.JTextField NomTextField;
    private javax.swing.JTextField PrenomTextField;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox<String> SearchCombo;
    private javax.swing.JComboBox<String> SectionCombo;
    private javax.swing.JTable StudentsTable;
    private javax.swing.JButton UpdateBtn;
    private com.toedter.calendar.JDateChooser jDateBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelStudent;
    // End of variables declaration//GEN-END:variables

    

    
}
